name: coverage

env:
  RUST_BACKTRACE: 1

jobs:
  codecov:
    name: codecov
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - uses: taiki-e/cache-cargo-install-action@v1
      with: { tool: cargo-tarpaulin }
    # TODO: check this outputs coverage file same as actions-rs/tarpaulin@v0.1
    - run: cargo --locked tarpaulin --all-features -- --skip 'proptest::' --out Xml --verbose
    - uses: codecov/codecov-action@v3
      with: { file: cobertura.xml }

on:
  push:
    branches: [prīmum]
  pull_request:
    branches: [prīmum]
  schedule:
  - cron: '0 0 * * 5'
